src/Entity/Chaton.php
<?php

namespace App\Entity;

use App\Repository\ChatonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatonRepository::class)
 */
class Chaton
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sterelise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Photo;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="chatons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Proprietaire::class, mappedBy="Chaton")
     */
    private $proprietaires;

    public function __construct()
    {
        $this->proprietaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function isSterelise(): ?bool
    {
        return $this->Sterelise;
    }

    public function setSterelise(bool $Sterelise): self
    {
        $this->Sterelise = $Sterelise;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection<int, Proprietaire>
     */
    public function getProprietaires(): Collection
    {
        return $this->proprietaires;
    }

    public function addProprietaire(Proprietaire $proprietaire): self
    {
        if (!$this->proprietaires->contains($proprietaire)) {
            $this->proprietaires[] = $proprietaire;
            $proprietaire->addChaton($this);
        }

        return $this;
    }

    public function removeProprietaire(Proprietaire $proprietaire): self
    {
        if ($this->proprietaires->removeElement($proprietaire)) {
            $proprietaire->removeChaton($this);
        }

        return $this;
    }


}

src/Form/ChatonType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Chaton;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChatonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Sterelise')
            ->add('Photo')
            ->add("Categorie",EntityType::class, [
                'class'=>Categorie::class,//Choix de la classe liée
                'choice_label'=>'titre', //Choix de ce qui sera affiché comme texte
                'multiple'=>false,
                'expanded'=>false
            ])
            ->add('OK',SubmitType::class,["label"=>"Ok"])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chaton::class,
        ]);
    }
}

src/Controller/ChatonsController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Chaton;
use App\Form\CategorieAjouterType;
use App\Form\ChatonsSupprimerType;
use App\Form\ChatonType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChatonsController extends AbstractController
{
    /**
     * @Route("/chatons", name="app_chatons")
     */
    public function index(): Response
    {
        return $this->render('chatons/index.html.twig', [
            'controller_name' => 'ChatonsController',
        ]);
    }

    /**
     * @Route ("/chaton/ajouter",name="chatons_ajouter")
     */
    public function ajouterChaton(ManagerRegistry $doctrine, Request $request)
    {
        $chaton = new Chaton();
        // si on arrive la, c'est qu' on a trouvé une categorie
        //on va créée le formulaire avec  ( il sera remplie avec ses valeurs)
        $form = $this->createForm(ChatonType::class, $chaton);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la ajouter dans la BDD
            $em->persist($chaton);
            //generer l'insert
            $em->flush();

            //retour a l'accueil
            return $this->redirectToRoute("app_home");
        }

        return $this->render('chatons/ajouter.html.twig', [
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route ("/chatons/modifier/{id}",name="chatons_modifier")
     */
    public function modifierCategorie($id, ManagerRegistry $doctrine, Request $request)
    {
        //recuperer la catégorie dans la BDD
        $chaton = $doctrine->getRepository(Chaton::class)->find($id);

        //si on n'a rien trouvé -> 404
        if (!$chaton) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        // si on arrive la, c'est qu' on atrouvé une categorie
        //on va créée le formulaire avec  ( il sera remplie avec ses valeurs)
        $form = $this->createForm(ChatonType::class, $chaton);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la ranger dans la BDD
            $em->persist($chaton);
            //generer l'insert
            $em->flush();

            //retour a l'accueil
            return $this->redirectToRoute("app_home");
        }

        return $this->render('chatons/modifier.html.twig', [
            'chaton' => $chaton,
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route ("/chatons/supprimer/{id}",name="chatons_supprimer")
     */
    public function supprimerChatons($id, ManagerRegistry $doctrine, Request $request)
    {
        //recuperer la catégorie dans la BDD
        $chaton = $doctrine->getRepository(Chaton::class)->find($id);

        //si on n'a rien trouvé -> 404
        if (!$chaton) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        // si on arrive la, c'est qu' on atrouvé une categorie
        //on va créée le formulaire avec  ( il sera remplie avec ses valeurs)
        $form = $this->createForm(ChatonType::class, $chaton);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la supprimer dans la BDD
            $em->remove($chaton);
            //generer l'insert
            $em->flush();

            //retour a l'accueil
            return $this->redirectToRoute("app_home");
        }

        return $this->render('chatons/supprimer.html.twig', [
            'categorie' => $chaton,
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route ("/chaton/{id}",name="chatons_afficher")
     */
    public function afficherChaton($id, ManagerRegistry $doctrine)
    {
        //recuperer la catégorie dans la BDD
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);

        //si on n'a rien trouvé -> 404
        if (!$categorie) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        return $this->render('chatons/afficher.html.twig', [
            'categories' => $categorie,
            "chatons" => $categorie->getChatons()
        ]);
    }
}

templates/chatons/afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <h2>Chatons</h2>
    <div class="flex-wrap" style="width: 100%; display: flex; flex-direction: row;">
        {% for c in chatons %}
            <div class="col col-3">
                <div class="card m-1"><img src="{{ c.photo }}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h3 class="card-title">
                            {{ c.Nom }}
                        </h3>
                        <a href="{{ path("chatons_modifier",{"id":c.id}) }}" class="d-inline p-1 btn btn-danger">Modifier Chatons</a>
                        <a href="{{ path("chatons_supprimer",{"id":c.id}) }}" class="d-inline p-1 btn btn-warning">Supprimer Chatons</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <br>
    <a href="{{ path("chatons_ajouter") }}" class="btn btn-warning">Ajouter Chatons</a>
{% endblock %}

templates/chatons/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h2>Ajouter un Chaton</h2>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/chatons/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ChatonsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/joeau/PhpstormProjects/SymfonyBDD_Groupe1/src/Controller/ChatonsController.php'|file_link(0) }}">src/Controller/ChatonsController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/joeau/PhpstormProjects/SymfonyBDD_Groupe1/templates/chatons/index.html.twig'|file_link(0) }}">templates/chatons/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/chatons/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h2>Modifier un Chaton</h2>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/chatons/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Etes-vous sur de vouloir supprimer ce chaton</h1>
        {{ form(formulaire) }}
        <a href="{{ path("app_home") }}" class="btn btn-warning">Annuler</a>
    </div>
{% endblock %}