src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=Chaton::class, mappedBy="Categorie", orphanRemoval=true)
     */
    private $chatons;

    public function __construct()
    {
        $this->chatons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Chaton>
     */
    public function getChatons(): Collection
    {
        return $this->chatons;
    }

    public function addChaton(Chaton $chaton): self
    {
        if (!$this->chatons->contains($chaton)) {
            $this->chatons[] = $chaton;
            $chaton->setCategorie($this);
        }

        return $this;
    }

    public function removeChaton(Chaton $chaton): self
    {
        if ($this->chatons->removeElement($chaton)) {
            // set the owning side to null (unless already changed)
            if ($chaton->getCategorie() === $this) {
                $chaton->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieAjouterType;
use App\Form\CategorieSupprimerType;
use App\Form\CategorieType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoriesController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(ManagerRegistry $doctrine, Request $request): Response
    {
        //création du formulaire d'ajout
        $categorie = new Categorie(); //on crée une categorie ville
        //On crée un fomulaire a partir de la classe CategorieType et de notre Objet vide
        $form = $this->createForm(CategorieType::class, $categorie);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la ranger dans la BDD
            $em->persist($categorie);
            //generer l'insert
            $em->flush();
        }


        //Pour aller chercher les catégories, je vais utiliser un repository
        //Pour me servir de doctrine j'ajoute le parametres $doctrine a la mathode
        $repo = $doctrine->getRepository(Categorie::class);
        $categories = $repo->findAll();


        return $this->render('categories/index.html.twig', [
            'categories' => $categories,
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route ("/categorie/modifier/{id}",name="categorie_modifier")
     */
    public function modifierCategorie($id, ManagerRegistry $doctrine, Request $request)
    {
        //recuperer la catégorie dans la BDD
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);

        //si on n'a rien trouvé -> 404
        if (!$categorie) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        // si on arrive la, c'est qu' on atrouvé une categorie
        //on va créée le formulaire avec  ( il sera remplie avec ses valeurs)
        $form = $this->createForm(CategorieType::class, $categorie);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la ranger dans la BDD
            $em->persist($categorie);
            //generer l'insert
            $em->flush();

            //retour a l'accueil
            return $this->redirectToRoute("app_home");
        }

        return $this->render('categories/modifier.html.twig', [
            'categorie' => $categorie,
            "formulaire" => $form->createView()
        ]);
    }

    /**
     * @Route ("/categorie/supprimer/{id}",name="categorie_supprimer")
     */
    public function supprimerCategorie($id, ManagerRegistry $doctrine, Request $request)
    {
        //recuperer la catégorie dans la BDD
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);

        //si on n'a rien trouvé -> 404
        if (!$categorie) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        // si on arrive la, c'est qu' on a trouvé une categorie
        //on va créée le formulaire avec  ( il sera remplie avec ses valeurs)
        $form = $this->createForm(CategorieSupprimerType::class, $categorie);

        //Gestion du retour du formulaire
        //on ajoute Request dans les parametres comme dans le projet precedent
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //le handLeRequest a rempli notre objet $categorie
            //qui n'est plus vite
            //pour sauvegarder, on va récupérer un entityManager de doctrine
            //qui comme son nom l'indique gere les entités
            $em = $doctrine->getManager();
            //on lui dit de la supprimer dans la BDD
            $em->remove($categorie);
            //generer l'insert
            $em->flush();

            //retour a l'accueil
            return $this->redirectToRoute("app_home");
        }

        return $this->render('categories/supprimer.html.twig', [
            'categorie' => $categorie,
            "formulaire" => $form->createView()
        ]);
    }

}

templates/categories/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Gestion des chatons BDD</h1>
        <table class="table table-striped">
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th></th>
            </tr>
            {% for c in categories %}
                <tr>
                    <td>{{ c.titre }}</td>
                    <td>{{ c.description }}</td>
                    <td>
                        <a href="{{path("categorie_modifier",{"id":c.id})}}" class="btn btn-primary">Modifier</a>
                        <a href="{{path("categorie_supprimer",{"id":c.id})}}" class="btn btn-danger">Supprimer</a>
                        <a href="{{path("chatons_afficher",{"id":c.id})}}" class="btn btn-warning">Chatons</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h2>Ajouter une catégorie</h2>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/categories/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>modifier la catégorie <i>{{ categorie.titre }}</i></h1>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/categories/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CategoriesController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Etes-vous sur de vouloir supprimer la categorie<i>{{ categorie.titre }}</i></h1>
        {{ form(formulaire) }}
        <a href="{{ path("app_home") }}" class="btn btn-warning">Annuler</a>
    </div>
{% endblock %}